#!/bin/sh
# Shortcuts
#

# Document
xwc_newlayer_="key shift ctrl n"

# Actions
xwc_copy_="key ctrl c"
xwc_paste_="key ctrl v"
xwc_undo_="key ctrl z"
xwc_redo_="key ctrl y"
xwc_zoomin_="key +"
xwc_zoomout_="key -"

# Tools
#xwc_move_="key space"
xwc_move_=""
xwc_eraser_="key shift e"
xwc_empty_=""



xsetwacom set "Wacom Intuos BT S Pen stylus" Area 0 0 15200 9500
xsetwacom set "Wacom Intuos BT S Pen stylus" Suppress 2
xsetwacom set "Wacom Intuos BT S Pen stylus" RawSample 4
xsetwacom set "Wacom Intuos BT S Pen stylus" Threshold 26
xsetwacom set "Wacom Intuos BT S Pen stylus" PressureCurve 0 0 100 100
xsetwacom set "Wacom Intuos BT S Pen stylus" TabletPCButton off 
xsetwacom set "Wacom Intuos BT S Pen stylus" Mode Absolute
xsetwacom set "Wacom Intuos BT S Pen stylus" Button 1 1
xsetwacom set "Wacom Intuos BT S Pen stylus" Button 2 $xwc_move_
xsetwacom set "Wacom Intuos BT S Pen stylus" Button 3 $xwc_empty_ # 3
xsetwacom set "Wacom Intuos BT S Pen stylus" Button 8 $xwc_empty_ # 8
xsetwacom set "Wacom Intuos BT S Pen stylus" ToolDebugLevel 0 
xsetwacom set "Wacom Intuos BT S Pen stylus" TabletDebugLevel 0
xsetwacom set "Wacom Intuos BT S Pen stylus" Touch off
xsetwacom set "Wacom Intuos BT S Pen stylus" Gesture off
xsetwacom set "Wacom Intuos BT S Pen stylus" ZoomDistance 0
xsetwacom set "Wacom Intuos BT S Pen stylus" ScrollDistance 0
xsetwacom set "Wacom Intuos BT S Pen stylus" TapTime 250 
xsetwacom set "Wacom Intuos BT S Pen stylus" Rotate none
xsetwacom set "Wacom Intuos BT S Pen stylus" BindToSerial 0
xsetwacom set "Wacom Intuos BT S Pen stylus" PressureRecalibration on
xsetwacom set "Wacom Intuos BT S Pen stylus" PanScrollThreshold 1300


# Define pad buttons
xsetwacom set "Wacom Intuos BT S Pad pad" Button 1 $xwc_undo_
xsetwacom set "Wacom Intuos BT S Pad pad" Button 2 $xwc_zoomin_ 
xsetwacom set "Wacom Intuos BT S Pad pad" Button 3 $xwc_zoomout_
xsetwacom set "Wacom Intuos BT S Pad pad" Button 8 $xwc_redo_
#xsetwacom set "Wacom Intuos BT S Pad pad" ToolDebugLevel 0
#xsetwacom set "Wacom Intuos BT S Pad pad" TabletDebugLevel 0
#xsetwacom set "Wacom Intuos BT S Pad pad" Suppress 2
#xsetwacom set "Wacom Intuos BT S Pad pad" RawSample 4
#xsetwacom set "Wacom Intuos BT S Pad pad" Mode Absolute
#xsetwacom set "Wacom Intuos BT S Pad pad" Gesture off
#xsetwacom set "Wacom Intuos BT S Pad pad" ZoomDistance 0
#xsetwacom set "Wacom Intuos BT S Pad pad" ScrollDistance 0
#xsetwacom set "Wacom Intuos BT S Pad pad" TapTime 250
#xsetwacom set "Wacom Intuos BT S Pad pad" Threshold 0
#xsetwacom set "Wacom Intuos BT S Pad pad" BindToSerial 0
xsetwacom set "Wacom Intuos BT S Pad pad" PanScrollThreshold 13
